#!/bin/bash

governor=$(cpufreq-info -c 0 | grep "The governor" | sed 's/^.*"\(\w\+\)".*$/\1/')

if [[ ${governor} == "powersave" ]]; then short_text=""; colour="#999999";
elif [[ ${governor} == "performance" ]]; then short_text=""; colour="#FFFFFF"
else exit 33;
fi

if [ ${BLOCK_BUTTON} == "1" ]; then
	short_text="${short_text} ($(lscpu | grep "CPU MHz:" | grep -Po "\d+.\d+") MHz)"
elif [ ${BLOCK_BUTTON} == "3" ]; then
	governor=$(zenity --list --text="Select CPU governor" --hide-header --column "Governor" powersave performance)
	[ ! -z ${governor} ] && gksudo ~/.scripts/set_cpu_governor ${governor}
fi

echo ${short_text}
echo ${short_text}
echo ${colour}

exit 0
