#!/bin/bash

#scrot /tmp/screenshot.png
#convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png

scrot -q 1 /tmp/screenshot.png --exec 'convert $f -blur 0x5 /tmp/screenshotblur.png'

i3lock -n -i /tmp/screenshotblur.png
