#!/bin/bash

screenshot="/tmp/screenshot.png"
padlock="/home/stefan/Pictures/padlock.png"

icon_overlay=
[ -f "${padlock}" ] && icon_overlay="${padlock} -gravity Center -composite -matte"

scrot ${screenshot}
convert ${screenshot} -scale 10% -scale 1000% ${icon_overlay} ${screenshot}

i3lock -n -u -i ${screenshot}
rm ${screenshot}
