#!/usr/bin/env bash

# Set this to the path where the encrypted image can be found.
IMAGE_PATH='/mnt/data'
# Set this nickname. This script will search for ${IMAGE_NICKNAME}.img and luksOpen it as ${IMAGE_NICKNAME}.
IMAGE_NICKNAME='vc'
# This specifies where the decrypted image file will be mounted.
IMAGE_MOUNTPOINT='/mnt/development'

if [[ -f ${IMAGE_MOUNTPOINT}/.mounted ]]; then
	echo "It looks like ${IMAGE_MOUNTPOINT}/.mounted exists, so there is nothing to do"
	exit 0
fi

IMAGE_FILE_PATH=${IMAGE_PATH}/${IMAGE_NICKNAME}.img
if [[ ! -f ${IMAGE_FILE_PATH} ]]; then
	echo "Couldn\'t find image file ${IMAGE_FILE_PATH}"
	exit 1
else
	echo "Decrypting and mounting image"
	sudo cryptsetup luksOpen ${IMAGE_FILE_PATH} ${IMAGE_NICKNAME}
	sudo mount /dev/mapper/${IMAGE_NICKNAME} ${IMAGE_MOUNTPOINT}
fi

if [[ ! -f ${IMAGE_MOUNTPOINT}/.mounted ]]; then
	echo "It looks like the mount was not successful. ${IMAGE_MOUNTPOINT}/.mounted couldn\'t be found"
fi

exit 0
