#!/bin/bash

usage() {
	echo "Usage:"
	echo
	echo "$(basename $0) <location>"
	echo
	echo "	location	office, remote"
}

wrong_usage() {
	usage
	exit 1
}

while [ $# != 0 ]; do
    case $1 in
        --help|-h) usage; exit 0 ;;
        -*) ;;
        *) break ;;
    esac
    shift
done

[ $# -eq 1 ] || wrong_usage

location=$1

copy_config() {
	local _location=${1:?}
	cp --force --symbolic-link ~/.ssh/config_${_location} ~/.ssh/config 
}

case ${location} in
	office|remote) copy_config ${location} ;;
	*) echo "Unknown location ${location}"; exit 1 ;;
esac
