#!/bin/bash

xrandr \
	--output eDP-1 --primary --mode 3200x1800 --pos 3840x360 --scale 1x1 --dpi 235 --rotate normal \
	--output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal --scale 2x2 \
	--output DP-1 --off \
	--output HDMI-2 --off
