#!/bin/sh

xrandr \
	--output DP-1 --primary --auto --pos 0x0 --scale 1.5x1.5 --dpi 100 \
	--output eDP-1 --auto --pos 3840x1900 --scale 1x1 --dpi 235 \
	--output HDMI-1 --off \
	--output HDMI-2 --off
